
import { Translations } from './types';

export const THEME_COLORS = {
  primary: '#3A86FF',   // Blue
  secondary: '#06D6A0', // Green
  accent: '#8338EC',    // Purple
  text: '#2E2E2E',      // Dark Grey
  border: '#BDBDBD',    // Light Grey
  surface: '#FFFFFF',
  background: '#F8FAFC',
  error: '#ef4444',
  warning: '#F59E0B',
};

export const TRANSLATIONS: Record<'en' | 'ar', Translations> = {
  en: {
    loginTitle: "Welcome Back",
    registerTitle: "Create Account",
    loginSubtitle: "Sign in to continue to your account",
    registerSubtitle: "Join us and start your journey",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email or Phone",
    phone: "Phone Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    gender: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    nationality: "Nationality",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    loginBtn: "Login",
    registerBtn: "Register",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    switchToLogin: "Login here",
    switchToRegister: "Register here",
    language: "Language",
    required: "This field is required",
    invalidEmail: "Invalid email format",
    passwordsNoMatch: "Passwords do not match",
    successLogin: "Login successful!",
    successRegister: "Registration successful!",
    loading: "Processing...",
    confirmAction: "Are you sure?",
    success: "Success",
    error: "Error",
    // Placeholders
    phEmail: "e.g. teacher@example.com",
    phPhone: "e.g. 512345678",
    phPassword: "••••••••",
    phName: "Enter your name",
    // Dashboard
    dashboard: "Dashboard",
    overview: "Overview",
    schedule: "Schedule",
    wallet: "Wallet",
    profile: "Profile",
    logout: "Logout",
    settings: "Settings",
    notifications: "Notifications",
    disputes: "Disputes",
    searchPlaceholder: "Search...",
    // Student Dashboard
    privateLessons: "Private Lessons",
    courses: "Courses",
    languageLearning: "Language Learning",
    mySchedule: "My Schedule",
    topTeachers: "Top Teachers",
    recommendedCourses: "Recommended Courses",
    lastBooking: "Last Booking",
    noBookings: "No upcoming bookings",
    bookAgain: "Book Again",
    viewAll: "View All",
    myCertificates: "My Certificates",
    myTransactions: "My Transactions",
    paymentMethods: "Payment Methods",
    // Admin Dashboard
    users: "Users",
    academicStructure: "Academic Structure",
    verifications: "Verifications",
    payoutRequests: "Payout Requests",
    payoutAmount: "Payout Amount",
    bankDetails: "Bank Details",
    approvePayout: "Approve Payout",
    rejectPayout: "Reject Payout",
    to: "To",
    uploadTransferReceipt: "Upload Transfer Receipt",
    clickToUploadReceipt: "Click to upload receipt",
    confirmApproval: "Confirm Approval",
    adminPanel: "Admin Panel",
    bookings: "Bookings",
    unverified: "Unverified",
    admin: "Admin",
    approve: "Approve",
    reject: "Reject",
    viewCertificate: "View Certificate",
    levels: "Education Levels",
    classes: "Classes",
    role: "Role",
    actions: "Actions",
    active: "Active",
    banned: "Banned",
    verified: "Verified",
    totalUsers: "Total Users",
    activeTeachers: "Active Teachers",
    revenue: "Revenue",
    totalBookings: "Total Bookings",
    userDistribution: "User Distribution",
    recentActivity: "Recent Activity",
    lastUpdated: "Last updated",
    chartComingSoon: "Charts integration coming soon",
    newRegistration: "New registration",
    studentJoined: "Student joined the platform",
    ago: "ago",
    minutes: "m",
    deleted: "Deleted",
    selectLevelFirst: "Select a level first",
    selectClassFirst: "Select a class first",
    noClassesFound: "No classes found",
    noSubjectsFound: "No subjects found",
    create: "Create",
    nameEn: "Name (English)",
    nameAr: "Name (Arabic)",
    activeStatus: "ACTIVE",
    inactiveStatus: "INACTIVE",
    update: "Update",
    phMathematics: "e.g. Mathematics",
    phRejectionReason: "e.g. Inappropriate content, poor image quality...",
    provideReason: "Please provide a reason",
    // Booking Flow
    bookNow: "Book Now",
    selectTime: "Select Time",
    selectPayment: "Select Payment Method",
    confirmBooking: "Confirm Booking",
    bookingSuccess: "Booking Confirmed Successfully!",
    pay: "Pay",
    // Filters
    filters: "Filters",
    priceRange: "Price Range",
    rating: "Rating",
    applyFilters: "Apply Filters",
    clearFilters: "Clear",
    subject: "Subject",
    reference: "Reference",
    student: "Student",
    allBookings: "All Bookings",
    noBookingsFound: "No bookings found matching filters.",
    confirmed: "Confirmed",
    // Overview
    totalEarnings: "Total Earnings",
    monthEarnings: "This Month",
    activeCourses: "Active Courses",
    upcomingLessons: "Upcoming Lessons",
    requestPayout: "Request Payout",
    welcomeBack: "Welcome back,",
    // Schedule
    addSlot: "Add Slot",
    available: "Available",
    booked: "Booked",
    online: "Online",
    presence: "In-Person",
    sar: "SAR",
    perHour: "/ hr",
    edit: "Edit",
    delete: "Delete",
    // Wallet & Banks
    balance: "Current Balance",
    pending: "Pending",
    history: "Transaction History",
    credit: "Credit",
    debit: "Debit",
    bankAccounts: "Bank Accounts",
    addBank: "Add Bank Account",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    iban: "IBAN",
    swift: "SWIFT Code (Optional)",
    currency: "Currency",
    withdrawAmount: "Withdrawal Amount",
    selectBank: "Select Bank Account",
    submitRequest: "Submit Request",
    phBankName: "e.g. Al Rajhi Bank",
    phIBAN: "SA...",
    phAmount: "0.00",
    // Cards
    cardHolder: "Card Holder Name",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    saveCard: "Save Card",
    deleteCard: "Remove Card",
    noCards: "No payment methods saved.",
    addNewCard: "Add New Card",
    // Profile
    editProfile: "Edit Profile",
    bio: "Biography",
    subjects: "Subjects",
    save: "Save Changes",
    cancel: "Cancel",
    uploadPhoto: "Upload Photo",
    markAllRead: "Mark all as read",
    noNotifications: "No new notifications",
    parties: "Parties",
    raisedBy: "Raised By",
    againstUser: "Against",
    resolve: "Resolve",
    noDisputesFound: "No disputes found.",
    // Bookings
    myBookings: "My Bookings",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    bookingDetails: "Booking Details",
    teacher: "Teacher",
    date: "Date",
    time: "Time",
    status: "Status",
    viewList: "View List",
    viewCalendar: "View Calendar",
    // Disputes
    openDispute: "Open Dispute",
    caseNumber: "Case No.",
    reason: "Reason",
    description: "Description",
    bookingRef: "Booking Reference",
    submitDispute: "Submit Dispute",
    disputeHistory: "Dispute History",
    phDisputeDesc: "Please describe the issue in detail...",
    // Register & Roles
    chooseAccount: "Choose Account Type",
    roleSelectionDesc: "Start by selecting your role on the platform",
    studentDesc: "Learn and develop your skills with elite teachers",
    teacherInstitute: "Teacher / Institute",
    teacherInstituteDesc: "Be part of our education platform and offer your courses",
    teacherDetailedDesc: "You can register as a private teacher, language instructor, course trainer, or as a training institute/center offering professional courses through our platform.",
    studentRegistration: "Student Registration",
    teacherRegistration: "Teacher Registration",
    continue: "Continue",
    back: "Back",
    // Teacher Profile Completion
    completeProfile: "Complete Your Profile",
    welcomeToEwan: "Welcome to Ewan! Please tell us how you would like to offer your services on the platform.",
    individualTeacher: "Individual Teacher",
    individualTeacherDesc: "Register as an independent teacher providing private lessons or training courses individually.",
    trainingInstitute: "Institute / Training Center",
    trainingInstituteDesc: "Register as a certified training center, language institute, or educational institution managing multiple teachers.",
    selectThisType: "Select this type",
    updating: "Updating... Please wait",
    // Admin Tabs Detail
    manageCourses: "Manage Courses",
    phSearchCourses: "Search courses or teachers...",
    allStatus: "All Status",
    course: "Course",
    category: "Category",
    featured: "Featured",
    unknown: "Unknown",
    viewDetails: "View Details",
    deactivate: "Deactivate",
    activate: "Activate",
    removeFeatured: "Remove Featured",
    markFeatured: "Mark Featured",
    rejectCourse: "Reject Course",
    rejectionReasonLabel: "Please provide a reason for rejecting this course. The teacher will be notified.",
    confirmRejection: "Confirm Rejection",
    teacherManagement: "Teacher Management",
    contact: "Contact",
    requestedService: "Requested Service",
    certificate: "Certificate",
    verify: "Verify",
    noFile: "No file",
    academicCertificate: "Academic Certificate",
    downloadCertificate: "Download Certificate",
    verifyTeacher: "Verify Teacher",
    printPdf: "Print / Save PDF",
    close: "Close",
    name: "Name",
    na: "N/A",
    details: "Details",
    view: "View",
    teacherProfile: "Teacher Profile",
    // Calendar
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    weekDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  ar: {
    loginTitle: "مرحبًا بعودتك",
    registerTitle: "إنشاء حساب",
    loginSubtitle: "سجل الدخول للمتابعة إلى حسابك",
    registerSubtitle: "انضم إلينا وابدأ رحلتك",
    firstName: "الاسم الأول",
    lastName: "الاسم الأخير",
    email: "البريد الإلكتروني أو رقم الهاتف",
    phone: "رقم الهاتف",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    gender: "الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    nationality: "الجنسية",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت كلمة المرور؟",
    loginBtn: "تسجيل الدخول",
    registerBtn: "تسجيل",
    haveAccount: "لديك حساب بالفعل؟",
    noAccount: "ليس لديك حساب؟",
    switchToLogin: "سجل دخولك هنا",
    switchToRegister: "سجل هنا",
    language: "اللغة",
    required: "هذا الحقل مطلوب",
    invalidEmail: "صيغة البريد الإلكتروني غير صحيحة",
    passwordsNoMatch: "كلمات المرور غير متطابقة",
    successLogin: "تم تسجيل الدخول بنجاح!",
    successRegister: "تم التسجيل بنجاح!",
    loading: "جاري المعالجة...",
    confirmAction: "هل أنت متأكد؟",
    success: "تم بنجاح",
    error: "خطأ",
    // Placeholders
    phEmail: "مثال: teacher@example.com",
    phPhone: "مثال: 512345678",
    phPassword: "••••••••",
    phName: "أدخل اسمك",
    // Dashboard
    dashboard: "لوحة التحكم",
    overview: "نظرة عامة",
    schedule: "الجدول الزمني",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    logout: "تسجيل خروج",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    disputes: "النزاعات",
    searchPlaceholder: "بحث...",
    // Student Dashboard
    privateLessons: "دروس خصوصية",
    courses: "الدورات",
    languageLearning: "تعلم اللغات",
    mySchedule: "جدولي",
    topTeachers: "أفضل المعلمين",
    recommendedCourses: "دورات مقترحة",
    lastBooking: "آخر حجز",
    noBookings: "لا توجد حجوزات قادمة",
    bookAgain: "حجز مجدداً",
    viewAll: "عرض الكل",
    myCertificates: "شهاداتي",
    myTransactions: "معاملاتي",
    paymentMethods: "طرق الدفع",
    // Admin Dashboard
    users: "المستخدمين",
    academicStructure: "الهيكل الأكاديمي",
    verifications: "طلبات التوثيق",
    payoutRequests: "طلبات السحب",
    payoutAmount: "مبلغ السحب",
    bankDetails: "تفاصيل البنك",
    approvePayout: "الموافقة على السحب",
    rejectPayout: "رفض السحب",
    to: "إلى",
    uploadTransferReceipt: "تحميل إيصال التحويل",
    clickToUploadReceipt: "انقر لتحميل الإيصال",
    confirmApproval: "تأكيد الموافقة",
    adminPanel: "لوحة الإدارة",
    bookings: "الحجوزات",
    unverified: "غير موثق",
    admin: "مسؤول",
    approve: "قبول",
    reject: "رفض",
    viewCertificate: "عرض الشهادة",
    levels: "المراحل الدراسية",
    classes: "الصفوف",
    role: "الدور",
    actions: "إجراءات",
    active: "نشط",
    banned: "محظور",
    verified: "موثق",
    totalUsers: "إجمالي المستخدمين",
    activeTeachers: "المعلمون النشطون",
    revenue: "الإيرادات",
    totalBookings: "إجمالي الحجوزات",
    userDistribution: "توزيع المستخدمين",
    recentActivity: "آخر النشاطات",
    lastUpdated: "آخر تحديث",
    chartComingSoon: "سيتم إضافة الرسوم البيانية قريباً",
    newRegistration: "تسجيل جديد",
    studentJoined: "انضم طالب جديد للمنصة",
    ago: "منذ",
    minutes: "د",
    deleted: "محذوف",
    selectLevelFirst: "اختر مرحلة أولاً",
    selectClassFirst: "اختر صفاً أولاً",
    noClassesFound: "لم يتم العثور على صفوف",
    noSubjectsFound: "لم يتم العثور على مواد",
    create: "إنشاء",
    nameEn: "الاسم (بالإنجليزي)",
    nameAr: "الاسم (بالعربي)",
    activeStatus: "نشط",
    inactiveStatus: "غير نشط",
    update: "تحديث",
    phMathematics: "مثال: الرياضيات",
    phRejectionReason: "مثال: محتوى غير لائق، جودة صورة ضعيفة...",
    provideReason: "يرجى تقديم سبب",
    // Booking Flow
    bookNow: "احجز الآن",
    selectTime: "اختر الوقت",
    selectPayment: "اختر طريقة الدفع",
    confirmBooking: "تأكيد الحجز",
    bookingSuccess: "تم تأكيد الحجز بنجاح!",
    pay: "دفع",
    // Filters
    filters: "تصفية النتائج",
    priceRange: "نطاق السعر",
    rating: "التقييم",
    applyFilters: "تطبيق التصفية",
    clearFilters: "مسح",
    subject: "المادة",
    reference: "المرجع",
    student: "الطالب",
    allBookings: "كل الحجوزات",
    noBookingsFound: "لم يتم العثور على حجوزات تطابق الفلترة.",
    confirmed: "مؤكد",
    // Overview
    totalEarnings: "مجموع الأرباح",
    monthEarnings: "هذا الشهر",
    activeCourses: "الدورات النشطة",
    upcomingLessons: "الدروس القادمة",
    requestPayout: "طلب سحب رصيد",
    welcomeBack: "مرحبًا،",
    // Schedule
    addSlot: "إضافة موعد",
    available: "متاح",
    booked: "محجوز",
    online: "أونلاين",
    presence: "حضوري",
    sar: "ر.س",
    perHour: "/ ساعة",
    edit: "تعديل",
    delete: "حذف",
    // Wallet & Banks
    balance: "الرصيد الحالي",
    pending: "قيد الانتظار",
    history: "سجل المعاملات",
    credit: "إيداع",
    debit: "خصم",
    bankAccounts: "الحسابات البنكية",
    addBank: "إضافة حساب بنكي",
    bankName: "اسم البنك",
    accountNumber: "رقم الحساب",
    iban: "رقم الآيبان (IBAN)",
    swift: "رمز السويفت (اختياري)",
    currency: "العملة",
    withdrawAmount: "مبلغ السحب",
    selectBank: "اختر الحساب البنكي",
    submitRequest: "إرسال الطلب",
    phBankName: "مثال: مصرف الراجحي",
    phIBAN: "SA...",
    phAmount: "0.00",
    // Cards
    cardHolder: "اسم حامل البطاقة",
    cardNumber: "رقم البطاقة",
    expiryDate: "تاريخ الانتهاء",
    cvv: "رمز التحقق (CVV)",
    saveCard: "حفظ البطاقة",
    deleteCard: "حذف البطاقة",
    noCards: "لا توجد طرق دفع محفوظة.",
    addNewCard: "إضافة بطاقة جديدة",
    // Profile
    editProfile: "تعديل الملف",
    bio: "نبذة عني",
    subjects: "المواد الدراسية",
    save: "حفظ التغييرات",
    cancel: "إلغاء",
    uploadPhoto: "رفع صورة",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات جديدة",
    parties: "الأطراف",
    raisedBy: "بواسطة",
    againstUser: "ضد",
    resolve: "حل النزاع",
    noDisputesFound: "لا توجد نزاعات.",
    // Bookings
    myBookings: "حجوزاتي",
    upcoming: "قادمة",
    completed: "مكتملة",
    cancelled: "ملغية",
    bookingDetails: "تفاصيل الحجز",
    teacher: "المعلم",
    date: "التاريخ",
    time: "الوقت",
    status: "الحالة",
    viewList: "عرض القائمة",
    viewCalendar: "عرض التقويم",
    // Disputes
    openDispute: "فتح نزاع",
    caseNumber: "رقم القضية",
    reason: "السبب",
    description: "الوصف",
    bookingRef: "مرجع الحجز",
    submitDispute: "إرسال النزاع",
    disputeHistory: "سجل النزاعات",
    phDisputeDesc: "يرجى وصف المشكلة بالتفصيل...",
    // Register & Roles
    chooseAccount: "اختر نوع الحساب",
    roleSelectionDesc: "ابدأ باختيار دورك في المنصة",
    studentDesc: "تعلم وطور مهاراتك مع نخبة من المعلمين",
    teacherInstitute: "معلم / معهد",
    teacherInstituteDesc: "كن جزءاً من منصتنا التعليمية وقدم دوراتك",
    teacherDetailedDesc: "يمكنك التسجيل كمعلم مستقل، مدرب لغات، مدرب دورات، أو كمعهد / مركز تدريب يقدم دورات مهنية عبر منصتنا.",
    studentRegistration: "تسجيل طالب",
    teacherRegistration: "تسجيل معلم",
    continue: "متابعة",
    back: "العودة",
    // Teacher Profile Completion
    completeProfile: "أكمل ملفك الشخصي",
    welcomeToEwan: "مرحباً بك في إيوان! يرجى إخبارنا كيف ترغب في تقديم خدماتك عبر المنصة.",
    individualTeacher: "معلم مستقل",
    individualTeacherDesc: "سجل كمعلم مستقل يقدم دروساً خصوصية أو دورات تدريبية بشكل فردي.",
    trainingInstitute: "معهد / مركز تدريب",
    trainingCenterDesc: "سجل كمركز تدريب معتمد، معهد لغات، أو مؤسسة تعليمية تدير عدة معلمين.",
    selectThisType: "اختر هذا النوع",
    updating: "جاري التحديث... يرجى الانتظار",
    // Admin Tabs Detail
    manageCourses: "إدارة الدورات",
    phSearchCourses: "البحث عن الدورات أو المعلمين...",
    allStatus: "كل الحالات",
    course: "الدورة",
    category: "الفئة",
    featured: "مميز",
    unknown: "غير معروف",
    viewDetails: "عرض التفاصيل",
    deactivate: "تعطيل",
    activate: "تفعيل",
    removeFeatured: "إزالة التمييز",
    markFeatured: "تمييز الدورة",
    rejectCourse: "رفض الدورة",
    rejectionReasonLabel: "يرجى تقديم سبب لرفض هذه الدورة. سيتم إخطار المعلم.",
    confirmRejection: "تأكيد الرفض",
    teacherManagement: "إدارة المعلمين",
    contact: "التواصل",
    requestedService: "الخدمة المطلوبة",
    certificate: "الشهادة",
    verify: "توثيق",
    noFile: "لا يوجد ملف",
    academicCertificate: "الشهادة الأكاديمية",
    downloadCertificate: "تحميل الشهادة",
    verifyTeacher: "توثيق المعلم",
    printPdf: "طباعة / حفظ PDF",
    close: "إغلاق",
    name: "الاسم",
    na: "غير متوفر",
    details: "التفاصيل",
    view: "عرض",
    teacherProfile: "ملف المعلم",
    // Calendar
    months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
    weekDays: ["أحد", "إثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
  },
};

export const COUNTRIES = [
  { code: "SA", label: "Saudi Arabia", flag: "🇸🇦" },
  { code: "AE", label: "United Arab Emirates", flag: "🇦🇪" },
  { code: "EG", label: "Egypt", flag: "🇪🇬" },
  { code: "KW", label: "Kuwait", flag: "🇰🇼" },
  { code: "QA", label: "Qatar", flag: "🇶🇦" },
  { code: "BH", label: "Bahrain", flag: "🇧🇭" },
  { code: "OM", label: "Oman", flag: "🇴🇲" },
  { code: "JO", label: "Jordan", flag: "🇯🇴" },
  { code: "US", label: "United States", flag: "🇺🇸" },
  { code: "UK", label: "United Kingdom", flag: "🇬🇧" },
  { code: "OT", label: "Other", flag: "🌍" }
];